### ISSUE TITLE
invalid package specified in requirements.txt

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/velox#2]
The requirements file [tries to install](https://github.com/indirectlylit/velox/blob/master/requirements.txt#L1) `pkg-resources==0.0.0`

which results in the error

```
Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 1))
```

* python version 3.6.5
* pip version 10.0.1
* macOS

This [appears to be a bug in Ubuntu](https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1635463), and removing the `pkg-resources` allows installation to proceed

**Comment by bonidukic** [comment]
Thanks for that - it has been removed from the `requirements.txt`.

Closing.
