### ISSUE TITLE
missing requirements file

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/velox#3]
The readme says to install postgres dependencies via

> `pip install -r requirements/postgres.txt`

but this file doesn't exist

**Comment by bonidukic** [comment]
@indirectlylit 

The sentence prior to the above mentioned one notes:

>To be able to run tests in the PostgreSQL context, you will have to install PostgreSQL and PostgresSQL related dependencies by running the following command **(using the Kolibri virtualenv)**

But I agree that it is not very clear - I'll update this section.

**Comment by bonidukic** [comment]
@indirectlylit please take a look and let me know if the updated section makes it less confusing now:

https://github.com/learningequality/velox#postgresql-optional

**Comment by indirectlylit** [comment]
thanks for the clarification.

I would maybe just amend it to specify both within the virtualenv _and_ within the kolibri directory (or repo). It maybe should be obvious, but it was that aspect which originally confused me

**Comment by bonidukic** [comment]
@indirectlylit I added the clarification as per your suggestion:

> Install Kolibri PostgresSQL related package dependencies by running the following command within the **Kolibri installation directory** (repository) and using the **Kolibri virtualenv** (as this is a Kolibri, not Velox, package requirement):

I'll be closing this now, feel free to re-open if you don't find this satisfactory.
